### ISSUE TITLE
Workflow triggers

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#153]
@brownoxford, I'm aligning to your 
```
on:
  workflow_dispatch:
```
But I think we need to talk about well-suited triggering mechanisms, don't we?

**Comment by brownoxford** [comment]
@nissimsan Yes, for sure. That's a bit of a holdover to ensure we don't accidentally leak secrets into published reports. We are moving in the right direction with #148.

I think that `push` and `workflow_dispatch` are appropriate, but `pull_request` could have some problems because GitHub will not pass secrets to runners in external repos, so many of those might fail. I tried adding a check at one point to see whether the initiating repo was "ours" before running during a `pull_request` event, but I didn't get it working properly. I'm sure there is a way to do it, just need to spend some time with it.
