### ISSUE TITLE
Should all DID resolution requests be unauthenticated?

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#187]
The new verifier DID resolution requests added to the presentation testing is unauthenticated - should we *always* make unauthenticated DID resolution requests?

@nissimsan @OR13 pinging for comment

**Comment by TallTed** [comment]
No, we should not always make unauthenticated DID resolution requests (all DID resolution requests should not be unauthenticated).

Both unauthenticated and authenticated DID resolution requests should be tested.

**Comment by OR13** [comment]
IMO, all our tests should require authentication, when we expect it to be used in a production use case... there are "open world" api scenarios we might consider, like the interactions between CHAPI and the presentation exchange APIs.... but thats probably better handled on a separate issue.

**Comment by mkhraisha** [comment]
I think we should switch to authenticated endpoints for all did-resolution postman tests.

**Comment by OR13** [comment]
Consensus is that everything should be authenticated.

We can close this when we have negative tests that confirm that all endpoints require auth.

**Comment by OR13** [comment]
We think 

`/presentations/available` and `/presentations/submissions` should NOT require authentication.

We think all other endpoints should require authentication with scopes.

**Comment by BenjaminMoe** [comment]
I agree with: https://github.com/w3c-ccg/traceability-interop/issues/187#issuecomment-1129181211

**Comment by BenjaminMoe** [comment]
Objections on the call was the the description needs to be updates, and we need to provide a list of end-points on this issue and provide a list of end points, and then provide rationality for why we think authentication should be required or not.

There's a second aspect of optionality. I agree that as a spec that we should avoid optionality. So we should provide rationale for how authentication could be applied if not required.

**Comment by nissimsan** [comment]
I completely agree, @OR13. I was just writing this: 
- DIDAuth presentation (`POST /presentations/available` and `POST /presentations/submissions`) MUST NOT have OAuth security.
- OAuth presentation (`POST /presentations`) MUST have OAuth security.

**Comment by TallTed** [comment]
from @OR13's use case 1 (https://github.com/w3c-ccg/traceability-interop/issues/187#issuecomment-1130042940)
> Alice resolves Bobs DID

To my eyes, that says "Alice requests resolution of Bob's DID" which I *think* is an unauthenticated request, given that authentication gets discussed later in that use case.  This DID resolution request is entirely independent of `/presentations/available` and `/presentations/submissions` because Alice doesn't know those endpoints exist until *after* Alice has resolved Bob's DID.

It's kind of like DNS resolution to IP address, which is typically unauthenticated, though any service requests (e.g., `ssh`, `ftp`) made to that IP address *may* require authentication (or may *not*, e.g., `http`).

**Comment by OR13** [comment]
> To my eyes, that says "Alice requests resolution of Bob's DID" which I think is an unauthenticated request, given that authentication gets discussed later in that use case. 

I focused my comments on `/presentations/available` and `/presentations/submissions` intentionally.

We can discuss security considerations of the other endpoints on a separate issue, each endpoint likely requires different scopes / attention.

... but you are not correct that "DID Resolution" requires "network requests" ... 

HTTP is just 1 way of doing DID resolution... you don't need to make any network requests to resolve did key, and you don't need a "trusted resolver" to resolve did web.

- https://did.key.transmute.industries/did:key:z6MkmmYt6Tj6TCVw3vJweFKt9D86w6FuBKiki6oy6nCjxcuM
- https://www.transmute.industries/.well-known/did.json

In fact, if you are really paranoid, you would avoid ever using any resolver other than one you operated yourself.

Because the network logs of resolvers leak information about the metadata of credentials (issuer and holder timings).

**Comment by OR13** [comment]
I can also update the title and description of this issue to focus it on `GET /identifiers/{did}`.

**Comment by nissimsan** [comment]
Discussing on the call: the three /presentations endpoints are the important ones to cover here, dealing directly with interoperability.

**Comment by nissimsan** [comment]
Consensus to close this general ticket and open individual per-endpoint issues.

**Comment by BenjaminMoe** [comment]
Since the other issues have been opened, i think this issue is safe to close.

**Comment by nissimsan** [comment]
Closing this, moving the discussion to the individual issues.
