### ISSUE TITLE
Define OAuth2 requirements for `/presentations/submissions`

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#242]
The goal of this issue is start discussion regarding the OAuth2 authentication requirements of the [`/presentations/submissions` endpoint](https://w3c-ccg.github.io/traceability-interop/openapi/#post-/presentations/submissions).  This issue stems from the discussion on #187, and can be considered complete when the following items are resolved:

_**Please note**: the following lists are displayed as GitHub task lists for visual effect, not to suggest that there are actually additional tasks to be done._

The state of the checkboxes in this description represent the in-progress resolution of this issue. Until the `ready-for-close` label is applied, this issue should be considered in-progress. __This issue `MUST NOT` be closed until corresponding issues have been opened to implement the relevant conformance testing and, if necessary, modify the openapi spec.__

**Goal 1: Explicitly state OAuth2 requirements for the `/presentations/submissions` endpoint**
_One, and only one, of these options `MUST` be selected._

- [ ] The `/presentations/submissions` endpoint MAY require OAuth2
- [ ] The `/presentations/submissions` endpoint MUST require OAuth2
- [x] The `/presentations/submissions` endpoint MUST NOT require OAuth2

**Goal 2: Explicitly define scope requirements for this endpoint when authentication is in use:**
_One or more of these options `MUST` be selected **unless** the `MUST NOT` option was selected in **Goal 1**, in which case these options `MUST NOT` be selected. For requests that require OAuth2, each of the selected scopes `MUST` be present in an OAuth2 bearer token in order for the request to be permitted._

The following list of OAuth2 scopes is pulled from the current `openapi.yaml` file. If additional scopes are needed for the `/presentations/submissions` endpoint, they should be added here and an issue should be created to ensure that `openapi.yaml` is updated.
- [ ] `resolve:dids`
- [ ] `issue:credentials`
- [ ] `verify:credentials`
- [ ] `read:credentials`
- [ ] `update:credentials`
- [ ] `prove:presentations`
- [ ] `verify:presentations`
- [ ] `submit:presentations`

**Comment by BenjaminMoe** [comment]
**Goal 1**

The `/presentations/submissions` endpoint MUST NOT require OAuth2

**Comment by TallTed** [comment]
> The `/presentations/available` endpoint MUST NOT require OAuth2

Justification? 

I'm sure I don't fully understand either OAuth2 or the currently popular split of endpoints, as listed in the several "Define OAuth2 requirements" issues, but to the degree I do, it seems to me there are conceivable situations where one might want to require authentication for all endpoints one makes available, including `/presentations/available`.  In itself, this might not require OAuth2, but I cannot see a reason to *forbid* OAuth2 for such use — which breaks from the _MUST NOT_ above.

So please, why must OAuth2 be forbidden for this use?

**Comment by BenjaminMoe** [comment]
>So please, why must OAuth2 be forbidden for this use?

`/presentations/available` and `/presentations/submissions` are a set that implicitly use did authorization.

![Presentations - Frame 1(2)](https://user-images.githubusercontent.com/86194145/173907162-3ce3c7a3-977b-4bef-b605-678c5b0303bf.jpg)

1. A holder sends a request to a verifier on the `/presentations/available` end point
2. The verifier end point returns a domain and challenge
3. The holder signs over the challenge
4. The holder sends the signed presentation on the `/presentations/submissions` end point to the verifier
5. The verifier verifies the presentation by checking the signed challenge (and can choose to reject the presentation if the signature is incorrect, if the signature is not signed by a white-listed did, or if the credentials included in the verification does not meet some criteria specified by the verifier). 
6. The verifier returns a response to indicate the presentation has either been accepted or rejected

The OAuth2 version of this flow is defined by the `/presentations` end-point. 

![Presentations - Frame 2](https://user-images.githubusercontent.com/86194145/173908108-9d60e7ce-7be1-4b29-ac9c-ca022d3c5b06.jpg)

A verifier supplies a holder with a `client_id` and `client_secret` to use for Authentication. The holder obtains a `token` with the `client_id` and `client_secret`. 

1. The holder sends a presentation to the verifier with the `token` provided by OAuth2
2. The verifier returns a response that indicates that the presentation has been accepted or rejected.

In this case the `token` is providing the functionality that the signature role previously played. Where because the verifier has provided a holder with a `client_id` and `client_secret` it is understood who the sender is, and a signature is not required to prove identification for this end-point. 

The reason that OAuth2 is forbidden by this end-point is because the authorization scheme is implied by the end-point definition. If you wanted to use the OAuth version of this flow you use `/presentations`, if you want to use the did-auth flow, you use 
`/presentations/available` + `/presentations/submissions`.

**Comment by nissimsan** [comment]
> The `/presentations/available` endpoint MUST NOT require OAuth2

+1 on this. 

This is a DIDAuth endpoint. OAuth on top of it would be double-authentication.

**Comment by TallTed** [comment]
@BenjaminMoe -- 

The large [comment](https://github.com/w3c-ccg/traceability-interop/issues/242#issuecomment-1156846715) is great!  I think something similar should be in each of these detailed issues, preferably as the first comment following the opener, if not as part of the opener itself, especially the last paragraph, i.e. --

> The reason that OAuth2 is forbidden by this end-point is because the authorization scheme is implied by the end-point definition. If you wanted to use the OAuth2 version of this flow you use `/presentations`, if you want to use the did-auth flow, you use `/presentations/available` + `/presentations/submissions`.


I do wonder why you're using checklists for the identified "Goals" (which don't seem like "Goals" to me, but I guess that's the term used in some programming methodology?).

"Goal 1" seems like a radio-button candidate, as when any one checkbox is ticked the others should not be -- i.e., they're all mutually exclusive.

"Goal 2" looks like it should have *something* checked, and that those checked items should be mentioned in the large [comment](https://github.com/w3c-ccg/traceability-interop/issues/242#issuecomment-1156846715), but maybe I'm misunderstanding something else?

-----

All that said, in https://github.com/w3c-ccg/traceability-interop/issues/242#issuecomment-1155501479, you still have --

> **Goal 1:**
> 
> The `/presentations/available` endpoint MUST NOT require OAuth2

-- which it appears, as @nissimsan noted (and as you have edited in several other comments on this issue), should be about `/presentations/submissions`, not `/presentations/available`.

**Comment by brownoxford** [comment]
OpenAPI documentation has been updated. Since OAuth2 is not required for this endpoint, we will not need to write specific negative testing to ensure that it is enabled. This can be closed out.

**Comment by nissimsan** [comment]
We did this.
