### ISSUE TITLE
Discuss internal holder vs external holder APIs

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#3]
should getting my "wallet contents" be in scope for internal holder apis.

Do we need to define these endpoints here or in the vc-http-api?

**Comment by mprorock** [comment]
Will likely be covered by vc-http-api is my sense and that work should be covered there to prevent duplicate efforts - my sense is that this spec should focus on cross trust boundary interop items that may be raised by additions to the vc-http-api

good call out from @OR13 on the weekly call - the api spec likely is covered best by the vc-http-api - the testing and validation of interop is covered by this spec - e.g. a test demonstrating trace use cases and credentials from the trace vocab between multiple parties hosting their own implementations of the vc-http-api using oauth for authentication, etc.

**Comment by OR13** [comment]
We're in a holding pattern waiting for the vc-http-api to split these holder apis up.

**Comment by TallTed** [comment]
As we've discussed on the API calls, all APIs should be designed as external.

(Why are APIs being discussed in the "interop" space, which I would have thought was mostly about data generation, transfer, and/or consumption?  Or, given that APIs are how "interop" happens, why are APIs being focused on _outside_ of the "interop" space?  It seems this split may have been made prematurely.)

Entities which don't care about some piece of the external security because they believe that all API callers coming from "internal" IP addresses (or whatever criteria) are automatically "safe" should be able to turn off enforcement of whatever "externally" focused elements they find problematic "internally".

**Comment by OR13** [comment]
I have proposal in the works for the vc-http-api that should help with this, this issue is blocked by taking that action, and making these holder APIs clearer.

**Comment by mkhraisha** [comment]
@OR13  would you be able to link to that proposal

**Comment by nissimsan** [comment]
@OR13 : mostly closed already. Suggest opening a more focused issue once interop has progressed further.

**Comment by OR13** [comment]
I think this issue was overtaken by events, we solved this in most recent PR.

These have been differentiated in the most recent PR: https://github.com/w3c-ccg/traceability-interop/pull/35
