### ISSUE TITLE
missing issuance options type conformance<>interop conflict

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#448]
`credentials_issue:options.type:missing` expects an error on this, but there are currently passing interop tests which would start failing if we enforce this.

**Comment by nissimsan** [comment]
@ipbyrne, which interop tests was it which would fail on this?

**Comment by brownoxford** [comment]
Right now, the OpenAPI spec [defines `options.type` as a required element ](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/IssueCredentialOptions.yml#L4-L5) of the request body for the `/credentials/issue` endpoint.

We should call out the `/credentials/issue` interoperability tests that are running without providing the `options.type` property in the request body so that this can be corrected.

**Comment by BenjaminMoe** [comment]
Proposal: Update the interop tests to conform to the conformance tests.

**Comment by OR13** [comment]
@nissimsan has this been resolved?

**Comment by nissimsan** [comment]
Yes, @ipbyrne's PR closes this
