### ISSUE TITLE
missing issuance options conformance<>interop conflict

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#449]
`credentials_issue:options:missing` expects an error on this, but there are currently passing interop tests which would start failing if we enforce this.

**Comment by brownoxford** [comment]
Right now, the OpenAPI spec [defines `options` as a required element ](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/resources/credential-issuer.yml#L16-L18)of the request body for the `/credentials/issue` endpoint.

We should call out the `/credentials/issue` interoperability tests that are running without providing the `options` property in the request body so that this can be corrected.

**Comment by nissimsan** [comment]
Interop test to be updated - similar to #448

**Comment by OR13** [comment]
@nissimsan  has this been resolved?

**Comment by nissimsan** [comment]
Yes, @ipbyrne's PR closes this
