### ISSUE TITLE
Align "workflows" concept in VC API and Traceability API

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/traceability-interop#589]
After months of discussion regarding the Exchanges section of the VC API, the group has settled on two terms that have consensus in that group; a "workflow" and an "exchange".

The *workflow* defines some business rules and defines one of the possible flows that users can go through. An *exchange* is a specific instance of a workflow that is bound to some sort of session with a client (e.g., Holder). You can read more about the discussions that led to this terminology here:

https://github.com/w3c-ccg/vc-api/issues/285#issuecomment-1679519613

We are also aware of the concept of workflows in the Traceability API and have endeavored to ensure that the concepts are aligned, and at this point, we believe that they are:

https://w3c-ccg.github.io/traceability-interop/draft/#workflows

The only difference is that it doesn't seem like the Traceability API defines endpoints for workflows and exchanges (which is fine, those endpoints are optional and Traceability can choose to implement their workflows through a different mechanism if they see fit, such as via the `/presentations/available` and `/presentations/submissions` endpoints).

This issue is just to ensure that the Traceability API group is aware of this latest decision and doesn't see any issue as implementers continue to implement VC API Exchanges.

**Comment by nissimsan** [comment]
Issue discussed on the call, mainly among Transmute and Mesur: No significant interest expressed in investing into ensuring alignment - at least not yet. Pending input from Mavennet on the topic.

**Comment by BenjaminMoe** [comment]
@mkhraisha please comment on this.

**Comment by OR13** [comment]
We'll need to update this, to account for key binding in SD-JWT... I suggest we close this for now.

**Comment by PatStLouis** [comment]
It was mentioned that the workflows endpoints in the traceability spec are mostly relating to enabling multiple presentations to be shared under a same exchange flow. Please correct me if I misunderstood @nissimsan . @msporny clarified that the intention of this issue is to ensure that the decisions of the vc-api employing the workflow terminology in this context is close enough to the workflow use case in the traceability spec so this term could be used in both spec without creating confusing and misalignment. This discussion will be continued in the vc-api call. I suggest leaving this issue open for a few more weeks before closing it and have a another short review before end of year to conclude.

**Comment by mkhraisha** [comment]
@PatStLouis to discuss with the VCAPI group about current understanding between two concepts.

**Comment by mkhraisha** [comment]
I think this issue can be closed as there is a new section to be added in #529 , the two separate specs are now clearly tackling different things and this should reduce any confusion
